config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  get "posts/top" => "posts#top"
  get "posts/map" =>"posts#map"
  resources :posts do
    resources :comments, only: %i(new show create edit update destroy)
    resources :likes, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :content, presence: true, length: { minimum: 2 }
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :picture, PictureUploader
    has_many :comments, dependent: :destroy
    validates :body, presence: true, length: { maximum: 1000 }    
    belongs_to :user
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
  validates :username, presence: true #追記
  validates :term, presence: true #追記
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :term])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :term])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        @comment = Comment.new
        @post = Post.find_by(id: params[:post_id])
    end
    
    def create
        #@post = Post.find(params[:post_id])
        @comment = Comment.new(comment_params)
        @comment.user_id = current_user.id
        if @comment.save
            redirect_to :root
        else
            render action: :new
        end
    end

    def edit
        @comment = Comment.find_by(id: params[:id])
        @post = Post.find_by(id: params[:post_id])
    end

    def update
        @comment = Comment.find_by(id: params[:id])
        if @comment.update_attributes(comment_params)
            redirect_to :root
        else
            redirect_to action: :edit
        end
    end

    def show
        @comment = Comment.find_by(id: params[:id])
    end


    def destroy
        @comment = Comment.find(params[:id])
        if @comment.destroy
            redirect_to :root
        else
            render:edit
        end
    end

 private
    def comment_params
        params.require(:comment).permit(:content, :post_id, :user_id)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController 
    
    def create
        @post = Post.find(params[:post_id])
        @alreadylike = Like.find_by(ip: request.remote_ip, post_id: params[:post_id])
        if @alreadylike
            redirect_back(fallback_location: root_path)
            flash[:notice] = "すでにいいねしています"
        else
            @like = Like.create(post_id: params[:post_id], ip: request.remote_ip)
            redirect_back(fallback_location: root_path)
        end
    end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!,except:[:index]
    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        if @post.save
            redirect_to allection: "index"        
        else
            redirect_to action: "new"
        end
    end

    def index
      @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to action: "new", :id =>@post.id
        else
            redirect_to action: "new"
        end
    end

    def destroy
        # Post.find(params[:id]).destroy
        # redirect_to action: "new"
        @post = Post.find(params[:id])
        if @post.destroy
            redirect_to action: "new"
        else
            render:edit
        end 
    end

private
    def post_params
        params.require(:post).permit(:body,:picture,:who,:url,:title) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
            
    require "uri"
       
       def text_url_to_link text
       
        URI.extract(text, ['http','https'] ).uniq.each do |url|
          sub_text = ""
          sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"
       
          text.gsub!(url, sub_text)
        end
       
        return text
      end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<div class="comment-page">

  <div class="comment-post">
    <i class="title">
      <i class="fas fa-square-full"> <%= @post.title %></i>
    <div class="second">
      <%= @post.user.username %>
      <%= @post.who %>
    </div><br>
    <div class="body-contents">
      <%= simple_format(h(@post.body)) %><br>
      <%= text_url_to_link(h( @post.url )).html_safe %><br>
      <%= image_tag @post.picture_url %><br>
    </div>
  </div>

  <div class="edit-comment-area">
    <%= form_with model: @comment, url: { action: :update }, html: { class: 'cardeditForm' }, local: true do |f| %>
    <%= f.text_area :content, class: "comment-form-control", placeholder: "コメント内容" %>
    <%= f.submit "編集する", class: "submitBtn" %>
    <% end %>
  </div>

</div>

app/views/comments/new.html.erb
<div class="comment-page">

  <div class="comment-post">
    <i class="title">
      <%= @post.title %></i>
    <div class="second">
      <%= @post.user.username %>
      <%= @post.who %>
    </div><br>
    <div class="body-contents">
      <%= simple_format(h(@post.body)) %><br>
      <%= text_url_to_link(h( @post.url )).html_safe %><br>
      <%= image_tag @post.picture_url %><br>
    </div>
  </div>

  <div class="comment-area">
    <%= form_with model: @comment, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f| %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <div class="cardnewForm_title">
      <%= f.text_area :content, autofocus: true, class: "comment-form-control", placeholder: "コメントを入力する" %>
      <%= f.submit "投稿する", class: "comment-submitBtn" %>
    </div>
    <% end %>
  </div>

</div>

app/views/comments/show.html.erb
<div class="cardContents_title-index">コメント</div>
<div class="cardContents_title-contenttitle"><%= @comment.content %></div>
<%= link_to '編集する', edit_post_comment_path(@comment.post, @comment), class: "edit_btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>大阪府立大学漕艇部BBS</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
    integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
</head>

<body>
  <%# ここにSlackでお送りした<head>たぐをぶちこんでください！ %>
  <header>
    <div class="row hdr">
      <div class="col-sm-5">
        <div class="header-left">
          <h1 class="header-title">大阪府立大学漕艇部BBS</h1>
          <h2 class="header-second-title"> Osaka Prefecture University Rowing Club</h2>
        </div>
      </div>
      <div class="col-sm-7">
        <div class="header-icons">
          <span class="fa-stack fa-2x">
            <%= link_to("/") do %>
            <i class="fas fa-circle fa-stack-2x "></i>
            <i class="fas fa-home fa-stack-1x fa-inverse"></i></span>
          <% end %>
          <span class="fa-stack fa-2x">
            <%= link_to("https://opurowingonline.wixsite.com/opurc") do %>
            <i class="fas fa-circle fa-stack-2x "></i>
            <i class="fab fas fa-desktop fa-stack-1x fa-inverse"></i></span>
          <% end %>
          <span class="fa-stack fa-2x">
            <%= link_to("https://twitter.com/opurowing") do %>
            <i class="fas fa-circle fa-stack-2x "></i>
            <i class="fab fa-twitter fa-stack-1x fa-inverse"></i></span>
          <% end %>
          <span class="fa-stack fa-2x">
            <%= link_to("https://www.instagram.com/opu_rowing.mg/") do %>
            <i class="fas fa-circle fa-stack-2x  "></i>
            <i class="fab fa-instagram fa-stack-1x fa-inverse"></i></span>
          <% end %>
          <span class="fa-stack fa-2x">
            <%= link_to("https://www.facebook.com/opurowing/") do %>
            <i class="fas fa-circle fa-stack-2x "></i>
            <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i></span>
          <% end %>
        </div>
      </div>
    </div>



  </header>
  <%= yield %>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
  </script>
  </div>
</body>

</html>

app/views/posts/edit.html.erb
<div class="edit-whole-area">
  <div class="edit-content-area"> <%# ② %>
    <div class="edit-post-area">
      <%= form_for @post do |f| %>
      <table class="access-table">
        <tbody>
          <tr>
            <th class="table-left">
              <p class="titlename">タイトル</p>
            </th>
            <th class="table-right">
              <%= f.text_field :title,class: "title-form" %><span class="margin-right first none"></span><%= f.radio_button :who, "現役"  %><%= f.label :who_現役, :現役,class: "labelbtn_geneki" %><span class="margin-right"></span><%= f.radio_button :who, "OB" %><%= f.label :who_ob, :OB,class: "labelbtn_ob" %></span>
            </th>
          </tr>
          
          <tr>
            <th class="table-left">
              <p>内容</p>
            </th>
            <th class="table-right">
              <%= f.text_area :body,class: "body-form"%>
              <%#  :size=>"20×10"%>
            </th>
          </tr>
          <tr>
            <th class="table-left">
              <p>URL</p>
            </th>
            <th class="table-right">
              <%= f.text_field :url,class: "url-form" %>
            </th>
          </tr>
          <tr>
            <th class="table-left">
              <p>画像</p>
            </th>
            <th class="table-right submit">
              <%= f.file_field :picture,class: "picture-form" %><%= f.submit "編集する",class: "submit-btn"%>
            </th>
          </tr>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="whole-area">
  <div class="content-area">
    <div class="post-content-area">
      <div class="posts-container">

        <div class="toko1">
          <div class="toko2">
            <%= link_to "投稿する", new_post_path, class:"to-ko-"%>
          </div>
          <% if user_signed_in? %>
          <div class="toko2">
            <%= link_to"ログアウト", destroy_user_session_path, method: :delete,class:"to-ko-" %>
          </div>
          <div class="toko2">
            <%= link_to"ユーザー編集", edit_user_registration_path, class:"to-ko-" %>
          </div>
          <% else %>
          <div class="toko2">
            <%= link_to"ログイン", new_user_session_path ,class:"to-ko-"%>
          </div>
          <% end %>
        </div>

        <% @posts.each do |t| %>
        <div class="post">
          <div class="titles">
            <i class="fas fa-square-full"> <%= t.title %></i>
          </div>
          <div class="seconds">
            <div class="second">
              <%= t.user.username %>
              <%= t.who %>
              <%= t.user.term %>期
            </div><br>
            <div class="body-contents">
              <%= simple_format(h(t.body)) %><br>
              <%= text_url_to_link(h( t.url )).html_safe %><br>
              <%= link_to t.picture.url, 'data-lightbox': t.picture do %>
              <%= image_tag t.picture.url if t.picture? %>
              <% end %>
            </div>
            <div class="icons">
              <p class="datetime"><%= t.created_at.to_s(:datetime_jp) %></p>
              <% if user_signed_in? && t.user.id==current_user.id%>
              <%= link_to(content_tag(:i,'',class: 'far fa-edit content-icon'), edit_post_path(t)) %>
              <%= link_to(content_tag(:i,'',class: 'far fa-trash-alt content-icon'), post_path(t), method: :delete, data:{confirm:"削除しますか？"}) %>
              <% end %>
              <%= link_to(content_tag(:i,'',class: 'fas fa-reply content-icon'), new_post_comment_path(t)) %>
            </div>
            <div class="comment-area">
              <% t.comments.each do |c| %><br>
              <div class="comment-contents">
                <i class="fas fa-caret-right"></i>
                <%= c.user.username %><br>
                <%= simple_format(h(c.content)) %><br>
                <div class="comment-icon">
                  <% if user_signed_in? && c.user_id == current_user.id %>
                    <%= link_to(content_tag(:i,'',class: 'far fa-edit content-icon'), edit_post_comment_path(t,c)) %>
                    <%= link_to(content_tag(:i,'',class: 'far fa-trash-alt content-icon'), post_comment_path(t,c), method: :delete, data:{confirm:"削除しますか？"}) %>
                  <% end %>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <%= paginate @posts %>
    </div>
    <div class="Tweet-infoarea"> <%# ②-② %>
      <a class="twitter-timeline" data-chrome=”transparentnoheadernofooter” data-border-color=”#ffffff”
        href="https://twitter.com/opurowing?ref_src=twsrc%5Etfw">Tweets by opurowing</a>
      <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="edit-whole-area">
  <div class="edit-content-area"> <%# ② %>
    <div class="edit_post">
      <%= form_for @post do |f| %>
      <table class="access-table">
        <tbody>
          <tr>
            <th class="table-left">
              <p class="titlename">タイトル</p>
            </th>
            <th class="table-right">
              <%= f.text_field :title,class: "title-form" %><span class="margin-right first none"></span><%= f.radio_button :who, "現役"  %><%= f.label :who_現役, :現役,class: "labelbtn_geneki" %><span class="margin-right"></span><%= f.radio_button :who, "OB" %><%= f.label :who_ob, :OB,class: "labelbtn_ob" %></span>
            </th>
          </tr>
          <tr>
            <th class="table-left">
              <p>内容</p>
            </th>
            <th class="table-right">
              <%= f.text_area :body,class: "body-form"%>
            </th>
          </tr>
          <tr>
            <th class="table-left">
              <p>URL</p>
            </th>
            <th class="table-right">
              <%= f.text_field :url,class: "url-form" %>
            </th>
          </tr>
          <tr>
            <th class="table-left">
              <p>画像</p>
            </th>
            <th class="table-right submit">
              <%= f.file_field :picture,class: "picture-form" %><%= f.submit "投稿する",class: "submit-btn"%>
            </th>
          </tr>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name),class:"linkto" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name),class:"linkto" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れた", new_password_path(resource_name),class:"linkto"%><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>